# Generated by Django 5.1 on 2026-03-29 19:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('owners', models.JSONField(blank=True, default=list)),
                ('stack_config', models.JSONField(blank=True, default=dict, help_text='language, framework, test_framework, build_tool')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_spec_sequence', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SpecRepoConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spec_repo_url', models.URLField(help_text='GitHub repo URL for specs')),
                ('branch', models.CharField(default='main', max_length=200)),
                ('encrypted_token', models.BinaryField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('waiting_approval', 'Waiting for Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('error', 'Error')], default='running', max_length=20)),
                ('current_agent', models.CharField(blank=True, default='', max_length=100)),
                ('user_request', models.TextField()),
                ('state_snapshot', models.JSONField(blank=True, default=dict)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_slug', models.CharField(help_text='e.g. org/backend', max_length=200)),
                ('paths', models.JSONField(blank=True, default=list)),
                ('encrypted_token', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='add_api.namespace')),
            ],
            options={
                'unique_together': {('namespace', 'repo_slug')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spec_id', models.CharField(db_index=True, max_length=50)),
                ('namespace', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='add_api.workflowrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('spec_id', 'version')},
            },
        ),
    ]
