# Generated by Django 5.1 on 2026-04-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidd_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('waiting_approval', 'Waiting for Approval'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('error', 'Error')], default='running', max_length=20),
        ),
    ]
