# Generated by Codex on 2026-04-02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidd_api", "0002_add_cancelled_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("waiting_approval", "Waiting for Approval"),
                    ("waiting_code_approval", "Waiting for Code Approval"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                    ("error", "Error"),
                ],
                default="running",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="GeneratedCode",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("files", models.JSONField(default=list)),
                ("tests", models.JSONField(default=list)),
                ("implementation_summary", models.TextField(blank=True, default="")),
                ("code_pr_url", models.URLField(blank=True, null=True)),
                ("code_pr_numbers", models.JSONField(default=list)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("spec", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="codes", to="aidd_api.generatedspec")),
                ("workflow_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="codes", to="aidd_api.workflowrun")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
