"""Code Publisher — pushes generated code to GitHub via Git Data API (atomic commits)."""

import structlog
import requests
from src.graph.state import WorkflowState
from src.github.service import (
    _headers, _parse_repo_owner_name, get_default_branch_sha,
    create_branch, create_pull_request, GITHUB_API,
)

logger = structlog.get_logger()


def code_publisher_agent(state: WorkflowState) -> dict:
    """Stage 7: Push generated code to target repositories and open PRs."""
    from src.graph.workflow import notify_sub_step  # late import to avoid circular dependency
    workflow_id = state.get("workflow_id", "")
    spec_id = state.get("spec_id", "")
    generated_files = state.get("generated_files", [])
    generated_tests = state.get("generated_tests", [])
    target_repos = state.get("target_repositories", [])
    implementation_summary = state.get("implementation_summary", "")
    test_results = state.get("test_results", {})

    # "passed" = verified; "skipped" = verification consciously disabled.
    # Anything else (failed/error) → open the PR as a DRAFT so it cannot be
    # merged without the explicit human override at the code approval gate.
    tests_ok = test_results.get("status") in ("passed", "skipped")

    logger.info("code_publisher_start", workflow_id=workflow_id, files=len(generated_files))

    if not generated_files:
        return {
            "current_agent": "code_publisher",
            "code_published": False,
            "code_pr_url": None,
            "code_pr_numbers": [],
        }

    # Merge code files and test files
    test_language = "python"
    if target_repos:
        test_language = (target_repos[0].get("stack_config") or {}).get("language", "python")
    all_files = list(generated_files)
    for t in generated_tests:
        all_files.append({
            "path": t["path"],
            "action": "create",
            "content": t["content"],
            "language": test_language,
        })

    code_pr_numbers = []

    from django.conf import settings

    # Code is generated against the first target repo only (see code_developer),
    # so publish only there — pushing the same files elsewhere would be wrong.
    for repo_info in target_repos[:1]:
        owner = repo_info["owner"]
        repo = repo_info["repo"]
        branch = repo_info.get("branch", "main")
        token = settings.GITHUB_PAT

        # --- Sub-step 1: Create Branch ---
        branch_name = f"code/{spec_id.lower()}"
        notify_sub_step(workflow_id, "code_publisher", "Create Branch", spec_id=spec_id,
                        detail=f"GET /repos/{owner}/{repo}/git/ref/heads/{branch} — fetching base SHA...")

        try:
            base_sha = get_default_branch_sha(owner, repo, branch, token)
            notify_sub_step(workflow_id, "code_publisher", "Create Branch", spec_id=spec_id,
                            detail=f"Base SHA: {base_sha[:8]}... — creating branch {branch_name}")
            create_branch(owner, repo, branch_name, base_sha, token)
            notify_sub_step(workflow_id, "code_publisher", "Create Branch", spec_id=spec_id,
                            detail=f"Branch {branch_name} created on {owner}/{repo}")
        except Exception as e:
            notify_sub_step(workflow_id, "code_publisher", "Create Branch", spec_id=spec_id,
                            detail=f"Failed: {str(e)[:80]}")
            logger.error("code_publisher_branch_failed", error=str(e), repo=f"{owner}/{repo}")
            continue

        # --- Sub-step 2: Atomic Commit (Git Data API) ---
        notify_sub_step(workflow_id, "code_publisher", "Atomic Commit", spec_id=spec_id,
                        detail=f"Creating {len(all_files)} blob(s) via Git Data API...")

        try:
            commit_sha = _atomic_commit(
                owner, repo, branch_name, base_sha, all_files,
                f"Implement {spec_id}\n\nAuto-generated by ADD Code Developer",
                token,
            )
            notify_sub_step(workflow_id, "code_publisher", "Atomic Commit", spec_id=spec_id,
                            detail=f"Commit {commit_sha[:8]}... pushed to {branch_name} ({len(all_files)} files)")
        except Exception as e:
            notify_sub_step(workflow_id, "code_publisher", "Atomic Commit", spec_id=spec_id,
                            detail=f"Commit failed: {str(e)[:80]}")
            logger.error("code_publisher_commit_failed", error=str(e), repo=f"{owner}/{repo}")
            continue

        # --- Sub-step 3: Open Pull Request ---
        notify_sub_step(workflow_id, "code_publisher", "Open Pull Request", spec_id=spec_id,
                        detail=f"POST /repos/{owner}/{repo}/pulls — [{spec_id}] Code implementation")

        try:
            pr_body = _render_code_pr_body(spec_id, implementation_summary, all_files, test_results)
            pr_title = f"[{spec_id}] Code implementation"
            if not tests_ok:
                pr_title = f"[TESTS FAILING] {pr_title}"
                notify_sub_step(workflow_id, "code_publisher", "Open Pull Request", spec_id=spec_id,
                                detail=f"Tests {test_results.get('status', '?')} — opening PR as DRAFT (merge requires gate approval)")
            pr = create_pull_request(
                owner, repo,
                pr_title,
                pr_body,
                branch_name, branch, token,
                draft=not tests_ok,
            )

            code_pr_numbers.append({
                "repo": f"{owner}/{repo}",
                "pr_number": pr["number"],
                "pr_url": pr["url"],
                "files": [f["path"] for f in all_files],
                "draft": not tests_ok,
            })

            notify_sub_step(workflow_id, "code_publisher", "Open Pull Request", spec_id=spec_id,
                            detail=f"PR #{pr['number']} created: {pr['url']}")
            logger.info("code_publisher_pr_created",
                        repo=f"{owner}/{repo}", pr_number=pr["number"])
        except Exception as e:
            notify_sub_step(workflow_id, "code_publisher", "Open Pull Request", spec_id=spec_id,
                            detail=f"PR creation failed: {str(e)[:80]}")
            logger.error("code_publisher_pr_failed", error=str(e), repo=f"{owner}/{repo}")

    # --- Sub-step 4: Save to Database ---
    notify_sub_step(workflow_id, "code_publisher", "Save to Database", spec_id=spec_id,
                    detail=f"Writing {len(generated_files)} code + {len(generated_tests)} test file(s) to GeneratedCode...")

    try:
        from src.add_api.models import WorkflowRun, GeneratedCode, GeneratedSpec
        wf = WorkflowRun.objects.get(workflow_id=workflow_id)
        spec = GeneratedSpec.objects.filter(spec_id=spec_id).first()

        GeneratedCode.objects.create(
            workflow_run=wf,
            spec=spec,
            files=[{"path": f["path"], "action": f.get("action", "create"),
                    "content": f["content"], "language": f.get("language", "")}
                   for f in generated_files],
            tests=[{"path": t["path"], "content": t["content"],
                    "test_type": t.get("test_type", "unit")}
                   for t in generated_tests],
            implementation_summary=implementation_summary,
            code_pr_url=code_pr_numbers[0]["pr_url"] if code_pr_numbers else None,
            code_pr_numbers=code_pr_numbers,
        )
        notify_sub_step(workflow_id, "code_publisher", "Save to Database", spec_id=spec_id,
                        detail=f"Saved to GeneratedCode — {len(code_pr_numbers)} PR(s) recorded")
    except Exception as e:
        notify_sub_step(workflow_id, "code_publisher", "Save to Database", spec_id=spec_id,
                        detail=f"DB save failed: {str(e)[:80]}")
        logger.error("code_publisher_db_save_failed", error=str(e))

    code_pr_url = code_pr_numbers[0]["pr_url"] if code_pr_numbers else None

    logger.info("code_publisher_complete",
                workflow_id=workflow_id, prs=len(code_pr_numbers))

    return {
        "current_agent": "code_publisher",
        "code_published": bool(code_pr_numbers),
        "code_pr_url": code_pr_url,
        "code_pr_numbers": code_pr_numbers,
    }


def _atomic_commit(owner: str, repo: str, branch: str, parent_sha: str,
                   files: list[dict], message: str, token: str) -> str:
    """Create an atomic multi-file commit using the Git Data API.

    Flow: create blobs → create tree → create commit → update ref
    """
    headers = _headers(token)

    # 1. Create blobs for each file
    tree_items = []
    for f in files:
        content = f.get("content", "")
        blob_resp = requests.post(
            f"{GITHUB_API}/repos/{owner}/{repo}/git/blobs",
            json={"content": content, "encoding": "utf-8"},
            headers=headers, timeout=30,
        )
        blob_resp.raise_for_status()
        blob_sha = blob_resp.json()["sha"]

        tree_items.append({
            "path": f["path"],
            "mode": "100644",
            "type": "blob",
            "sha": blob_sha,
        })

    # 2. Get current tree SHA for the branch
    branch_ref = requests.get(
        f"{GITHUB_API}/repos/{owner}/{repo}/git/ref/heads/{branch}",
        headers=headers, timeout=30,
    )
    branch_ref.raise_for_status()
    current_sha = branch_ref.json()["object"]["sha"]

    commit_data = requests.get(
        f"{GITHUB_API}/repos/{owner}/{repo}/git/commits/{current_sha}",
        headers=headers, timeout=30,
    )
    commit_data.raise_for_status()
    base_tree_sha = commit_data.json()["tree"]["sha"]

    # 3. Create tree
    tree_resp = requests.post(
        f"{GITHUB_API}/repos/{owner}/{repo}/git/trees",
        json={"base_tree": base_tree_sha, "tree": tree_items},
        headers=headers, timeout=30,
    )
    tree_resp.raise_for_status()
    tree_sha = tree_resp.json()["sha"]

    # 4. Create commit
    commit_resp = requests.post(
        f"{GITHUB_API}/repos/{owner}/{repo}/git/commits",
        json={"message": message, "tree": tree_sha, "parents": [current_sha]},
        headers=headers, timeout=30,
    )
    commit_resp.raise_for_status()
    new_commit_sha = commit_resp.json()["sha"]

    # 5. Update branch ref
    requests.patch(
        f"{GITHUB_API}/repos/{owner}/{repo}/git/refs/heads/{branch}",
        json={"sha": new_commit_sha},
        headers=headers, timeout=30,
    ).raise_for_status()

    logger.info("atomic_commit_complete",
                repo=f"{owner}/{repo}", branch=branch,
                files=len(files), sha=new_commit_sha[:8])
    return new_commit_sha


def _render_code_pr_body(spec_id: str, summary: str, files: list[dict],
                         test_results: dict = None) -> str:
    """Render the code PR description."""
    file_list = "\n".join(f"- `{f['path']}` ({f.get('action', 'create')})" for f in files)

    warning = ""
    status = (test_results or {}).get("status")
    if status not in ("passed", "skipped", None):
        warning = (
            f"> ⚠️ **Tests {status} — opened as DRAFT.** This PR cannot be merged until "
            f"a human approves it at the ADD code approval gate (which marks it ready "
            f"and merges), or rejects it to trigger regeneration.\n\n"
        )

    return f"""{warning}## Code Implementation: {spec_id}

{summary}

### Files Changed
{file_list}

---

*This PR was automatically generated by the ADD Code Developer agent.*
*Review the implementation and approve to proceed with merge.*
"""
